package report

import (
	"fmt"
	"io"
	"text/template"
)

const shellTemplate = `#!/usr/bin/env bash
# This file was autogenerated by mlt3 mltlint
# Your command line was: {{.Args}}

DUPS_DIR="{{.Dups}}"

handle_emptydir() { :; }
handle_emptyfile() { :; }
original_cmd() { :; }

move_cmd() {
  local duplicate="$1"
  local original="$2"
  local dest="$3"
  if [ ! -e "$original" ]; then
    echo "SKIP (original missing): $original"
    return
  fi
  local dest_dir
  dest_dir="$(dirname "$dest")"
  mkdir -p "$dest_dir"
  mv "$duplicate" "$dest"
}

######### START OF AUTOGENERATED OUTPUT #########
{{range .Groups}}
original_cmd '{{.Original.Path}}' # original
{{- range .Duplicates}}
move_cmd '{{.Duplicate.Path}}' '{{.Original.Path}}' '{{$.Dups}}/{{.Level}}/{{.Duplicate.RelativePath}}' # {{.Level}} (dist={{.Distance}})
{{- end}}
{{end}}
######### END OF AUTOGENERATED OUTPUT #########
`

type shellData struct {
	Args   string
	Dups   string
	Groups []*Group
}

// WriteShell writes a bash script with move_cmd calls to w.
func WriteShell(w io.Writer, cfg Config, groups []*Group) error {
	tmpl, err := template.New("shell").Parse(shellTemplate)
	if err != nil {
		return fmt.Errorf("parse shell template: %w", err)
	}
	data := shellData{
		Args:   cfg.Args,
		Dups:   cfg.Dups,
		Groups: groups,
	}
	return tmpl.Execute(w, data)
}
